import AXIOS from '../config/axios.config';
import { headers, URL } from './constants';

export const Postgraduate = {

  getPostgraduateList() {
    return AXIOS.get(`${URL.POSTGRADUATE}`, {
      headers: headers(),
    })
      .then(response => {
        return response.data;
      })
      .catch(error => {
        if (error && error.response && error.response.data)
          return Promise.reject(error.response.data.message);
        return Promise.reject('Ups! Al parecer hay un error desconocido.');
      });
  },
  findPostgraduateById(id) {
    return AXIOS.get(`${URL.POSTGRADUATE}/${id}`, {
      headers: headers(),
    })
      .then(response => {
        return response.data;
      })
      .catch(error => {
        if (error && error.response && error.response.data)
          return Promise.reject(error.response.data.message);
        return Promise.reject('Ups! Al parecer hay un error desconocido.');
      });
  },
  update(postgraduate) {
    return AXIOS.put(`${URL.POSTGRADUATE}/${postgraduate.id}`, postgraduate, {
      headers: headers(),
    })
      .then(response => {
        return response.data;
      })
      .catch(error => {
        if (error && error.response && error.response.data)
          return Promise.reject(error.response.data.message);
        return Promise.reject('Ups! Al parecer hay un error desconocido.');
      });
  },

  savePostgraduate(postgraduate) {
    return AXIOS.post(`${URL.POSTGRADUATE}`, postgraduate, {
      headers: headers(),
    })
      .then(response => {
        return response.data;
      })
      .catch(error => {
        if (error && error.response && error.response.data)
          return Promise.reject(error.response.data.message);
        return Promise.reject('Ups! Al parecer hay un error desconocido.');
      });
  },
  delete(postgraduateId) {
    return AXIOS.delete(`${URL.POSTGRADUATE}/${postgraduateId}`, {
      headers: headers(),
    })
      .then(response => {
        return response.data;
      })
      .catch(error => {
        if (error && error.response && error.response.data)
          return Promise.reject(error.response.data.message);
        return Promise.reject('Ups! Al parecer hay un error desconocido.');
      });
  },
};

export default Postgraduate;
